---
- name: learn variable declaration and usage inside playbook
  hosts: all
  become: yes
  vars: 
    package: apache2
    user_allowed: true
    
  tasks:
   - name: we are unstall "{{package}}"
     apt:
      name: "{{package}}"
      state: absent
   - name: should not present "{{package}}"
     service:
      name: apache2
      state: stopped  
